name: TEST - Gradle - Terms of Service approval verification

on:
  pull_request:

permissions:
  pull-requests: write
  actions: write
  statuses: write

jobs:
  gradle-check-tos:
    uses: ./.github/workflows/check-tos.yml
    with:
      tos-location: 'https://foo.bar/tos.html'
      white-list: '*'
